
# makefsdata.ps1
# Generate fsdata.c for LwIP 2.1.x httpd from files in Core/Src/fs/
#
# Config in this project:
#   LWIP_HTTPD_DYNAMIC_HEADERS = 1  -> files do NOT include HTTP headers
#   LWIP_HTTPD_SSI              = 1  -> .shtml files use SSI tags
#
# Usage (from project root):
#   .\makefsdata.ps1
#
# Output: Middlewares\Third_Party\LwIP\src\apps\http\fsdata.c
#         (included by fs.c via #include HTTPD_FSDATA_FILE → "fsdata.c")

param(
    [string]$FsDir    = "Core\Src\fs",
    [string]$OutFile  = "Middlewares\Third_Party\LwIP\src\apps\http\fsdata.c"
)

$ErrorActionPreference = "Stop"

# -----------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------
function ConvertTo-Varname([string]$urlPath) {
    # "/index.shtml" -> "index_shtml"
    return ($urlPath -replace '^/', '' -replace '[^a-zA-Z0-9]', '_')
}

# -----------------------------------------------------------------------
# Collect files
# -----------------------------------------------------------------------
$fsRoot = Resolve-Path $FsDir
$files  = Get-ChildItem -Path $fsRoot -File -Recurse | Sort-Object FullName

if ($files.Count -eq 0) {
    Write-Error "No files found in $FsDir"
    exit 1
}

Write-Host "Found $($files.Count) file(s) in $FsDir"

# -----------------------------------------------------------------------
# Build output
# -----------------------------------------------------------------------
$sb = [System.Text.StringBuilder]::new()

$NL = "`n"

$null = $sb.Append(@"
/*
 * fsdata.c - auto-generated by makefsdata.ps1
 * LwIP 2.1.x  |  LWIP_HTTPD_DYNAMIC_HEADERS=1  (no embedded HTTP headers)
 * Source folder: $FsDir
 */
#include "lwip/apps/fs.h"
#include "lwip/def.h"

#define file_NULL (struct fsdata_file *) NULL

#ifndef FS_FILE_FLAGS_HEADER_INCLUDED
#define FS_FILE_FLAGS_HEADER_INCLUDED 1
#endif
#ifndef FS_FILE_FLAGS_HEADER_PERSISTENT
#define FS_FILE_FLAGS_HEADER_PERSISTENT 0
#endif

/* FSDATA_FILE_ALIGNMENT: 0=off */
#ifndef FSDATA_FILE_ALIGNMENT
#define FSDATA_FILE_ALIGNMENT 0
#endif
#ifndef FSDATA_ALIGN_PRE
#define FSDATA_ALIGN_PRE
#endif
#ifndef FSDATA_ALIGN_POST
#define FSDATA_ALIGN_POST
#endif

"@)

$varnames = [System.Collections.Generic.List[string]]::new()
$urlpaths = [System.Collections.Generic.List[string]]::new()
$pathLens = [System.Collections.Generic.List[int]]::new()

foreach ($file in $files) {
    # Build URL path: relative to fs dir, forward slashes, leading /
    $rel = $file.FullName.Substring($fsRoot.Path.Length).Replace('\', '/')
    if (-not $rel.StartsWith('/')) { $rel = '/' + $rel }

    $varname = ConvertTo-Varname $rel
    $varnames.Add($varname)
    $urlpaths.Add($rel)

    # Path bytes: URL string + null terminator
    $pathBytes = [System.Text.Encoding]::ASCII.GetBytes($rel) + [byte]0
    $pathLen   = $pathBytes.Length

    # File content bytes (raw - no HTTP header; DYNAMIC_HEADERS=1)
    $contentBytes = [System.IO.File]::ReadAllBytes($file.FullName)

    # Total data = path bytes + content bytes
    $allBytes = $pathBytes + $contentBytes

    $pathLens.Add($pathLen)

    # ---- Emit data array ----
    $null = $sb.Append("static const unsigned char FSDATA_ALIGN_PRE data_${varname}[] FSDATA_ALIGN_POST = {$NL")
    $null = $sb.Append("/* $rel ($pathLen chars) */$NL")

    # Path bytes on one line
    $hexPath = ($pathBytes | ForEach-Object { "0x{0:x2}" -f $_ }) -join ","
    $null = $sb.Append("$hexPath,$NL")

    # Content bytes, 16 per line
    $null = $sb.Append("/* raw file data ($($contentBytes.Length) bytes) */$NL")
    for ($i = 0; $i -lt $contentBytes.Length; $i += 16) {
        $end   = [Math]::Min($i + 15, $contentBytes.Length - 1)
        $chunk = $contentBytes[$i..$end]
        $hex   = ($chunk | ForEach-Object { "0x{0:x2}" -f $_ }) -join ","
        $null  = $sb.Append("$hex,$NL")
    }

    $null = $sb.Append("};$NL$NL")

    Write-Host "  + $rel  ($($contentBytes.Length) bytes)"
}

# ---- Emit struct entries ----
for ($i = 0; $i -lt $varnames.Count; $i++) {
    $varname = $varnames[$i]
    $plen    = $pathLens[$i]
    $prev    = if ($i -eq 0) { "file_NULL" } else { "file_$($varnames[$i-1])" }

    # DYNAMIC_HEADERS=1 -> flags = 0 (no FS_FILE_FLAGS_HEADER_INCLUDED)
    $null = $sb.Append(@"
const struct fsdata_file file_${varname}[] = { {
  ${prev},
  data_${varname},
  data_${varname} + ${plen},
  sizeof(data_${varname}) - ${plen},
  0 /* flags: no embedded HTTP header (LWIP_HTTPD_DYNAMIC_HEADERS=1) */
} };

"@)
}

# ---- FS_ROOT and FS_NUMFILES ----
$lastVar = $varnames[$varnames.Count - 1]
$null = $sb.Append("#define FS_ROOT     file_${lastVar}$NL")
$null = $sb.Append("#define FS_NUMFILES $($varnames.Count)$NL")

# -----------------------------------------------------------------------
# Write file (ASCII, LF line endings)
# -----------------------------------------------------------------------
$content = $sb.ToString()
[System.IO.File]::WriteAllText(
    (Join-Path (Get-Location) $OutFile),
    $content,
    [System.Text.Encoding]::ASCII
)

Write-Host ""
Write-Host "Generated: $OutFile  ($($varnames.Count) file(s))"
